import type {
  ArticleSummary,
  CollectionSummary,
  PageSummary,
  ProductSummary,
  ShopInfo,
} from "./queries";

// ─────────────────────────────────────────────────────────────────────
// Pure content generators. No I/O. Easy to unit-test later.
// All paths use Shopify's `template_suffix=machine` convention.
// ─────────────────────────────────────────────────────────────────────

const MACHINE_PARAM = "?view=machine";

const stripHtml = (s: string): string =>
  s
    .replace(/<[^>]+>/g, " ")
    .replace(/\s+/g, " ")
    .trim();

const truncate = (s: string, n: number): string =>
  s.length <= n ? s : `${s.slice(0, n - 1).trimEnd()}…`;

const productPath = (p: ProductSummary) => `/products/${p.handle}`;
const collectionPath = (c: CollectionSummary) => `/collections/${c.handle}`;
const pagePath = (p: PageSummary) => `/pages/${p.handle}`;
const articlePath = (a: ArticleSummary) =>
  `/blogs/${a.blogHandle}/${a.handle}`;

// ─── llms.txt — the index ────────────────────────────────────────────

export function generateLlmsTxt(args: {
  shop: ShopInfo;
  products: ProductSummary[];
  collections: CollectionSummary[];
  pages: PageSummary[];
  articles: ArticleSummary[];
}): string {
  const { shop, products, collections, pages, articles } = args;
  const lines: string[] = [];

  lines.push(`# ${shop.name}`);
  lines.push("");
  if (shop.description) {
    lines.push(`> ${shop.description.replace(/\s+/g, " ").trim()}`);
    lines.push("");
  }
  lines.push(`Storefront: ${shop.url}`);
  lines.push("");

  if (products.length) {
    lines.push("## Products");
    for (const p of products) {
      const summary = truncate(stripHtml(p.description) || p.productType || "", 140);
      const price =
        p.priceRangeFrom && p.currencyCode
          ? ` — ${p.currencyCode} ${p.priceRangeFrom}`
          : "";
      lines.push(`- [${p.title}](${productPath(p)}${MACHINE_PARAM})${price}${summary ? `: ${summary}` : ""}`);
    }
    lines.push("");
  }

  if (collections.length) {
    lines.push("## Collections");
    for (const c of collections) {
      const summary = truncate(stripHtml(c.description), 140);
      lines.push(
        `- [${c.title}](${collectionPath(c)}${MACHINE_PARAM})${summary ? `: ${summary}` : ""}`,
      );
    }
    lines.push("");
  }

  if (pages.length) {
    lines.push("## Pages");
    for (const p of pages) {
      const summary = truncate(stripHtml(p.bodySummary), 140);
      lines.push(
        `- [${p.title}](${pagePath(p)}${MACHINE_PARAM})${summary ? `: ${summary}` : ""}`,
      );
    }
    lines.push("");
  }

  if (articles.length) {
    lines.push("## Articles");
    for (const a of articles) {
      const summary = truncate(stripHtml(a.summary), 140);
      lines.push(
        `- [${a.title}](${articlePath(a)}${MACHINE_PARAM})${summary ? `: ${summary}` : ""}`,
      );
    }
    lines.push("");
  }

  lines.push("---");
  lines.push("");
  lines.push(
    "_This page is the AI-readable index for this store. Generated by AutoAEO._",
  );
  lines.push(`_Last updated: ${new Date().toISOString()}_`);

  return lines.join("\n");
}

// ─── llms-full.txt — concatenated full corpus ────────────────────────

export function generateLlmsFullTxt(args: {
  shop: ShopInfo;
  products: ProductSummary[];
  collections: CollectionSummary[];
  pages: PageSummary[];
  articles: ArticleSummary[];
}): string {
  const { shop, products, collections, pages, articles } = args;
  const out: string[] = [];

  out.push(`# ${shop.name}`);
  out.push("");
  if (shop.description) out.push(shop.description);
  out.push("");
  out.push(`Storefront: ${shop.url}`);
  out.push("");

  if (products.length) {
    out.push("# Products");
    out.push("");
    for (const p of products) {
      out.push(`## ${p.title}`);
      out.push("");
      const meta: string[] = [];
      if (p.priceRangeFrom && p.currencyCode) {
        const price =
          p.priceRangeFrom === p.priceRangeTo
            ? `${p.currencyCode} ${p.priceRangeFrom}`
            : `${p.currencyCode} ${p.priceRangeFrom}–${p.priceRangeTo}`;
        meta.push(`**Price:** ${price}`);
      }
      if (p.vendor) meta.push(`**Vendor:** ${p.vendor}`);
      if (p.productType) meta.push(`**Type:** ${p.productType}`);
      if (p.tags.length) meta.push(`**Tags:** ${p.tags.join(", ")}`);
      meta.push(`**URL:** ${shop.url}${productPath(p)}`);
      out.push(meta.join("  \n"));
      out.push("");
      const desc = stripHtml(p.description);
      if (desc) {
        out.push(desc);
        out.push("");
      }
      out.push("---");
      out.push("");
    }
  }

  if (collections.length) {
    out.push("# Collections");
    out.push("");
    for (const c of collections) {
      out.push(`## ${c.title}`);
      out.push("");
      out.push(`**URL:** ${shop.url}${collectionPath(c)}`);
      if (c.productsCount != null) {
        out.push(`**Products:** ${c.productsCount}`);
      }
      out.push("");
      const desc = stripHtml(c.description);
      if (desc) {
        out.push(desc);
        out.push("");
      }
      out.push("---");
      out.push("");
    }
  }

  if (pages.length) {
    out.push("# Pages");
    out.push("");
    for (const p of pages) {
      out.push(`## ${p.title}`);
      out.push("");
      out.push(`**URL:** ${shop.url}${pagePath(p)}`);
      out.push("");
      const body = stripHtml(p.bodySummary);
      if (body) {
        out.push(body);
        out.push("");
      }
      out.push("---");
      out.push("");
    }
  }

  if (articles.length) {
    out.push("# Articles");
    out.push("");
    for (const a of articles) {
      out.push(`## ${a.title}`);
      out.push("");
      out.push(`**URL:** ${shop.url}${articlePath(a)}`);
      if (a.publishedAt) {
        out.push(`**Published:** ${a.publishedAt}`);
      }
      out.push("");
      const body = stripHtml(a.summary);
      if (body) {
        out.push(body);
        out.push("");
      }
      out.push("---");
      out.push("");
    }
  }

  return out.join("\n");
}

// ─── Theme files for the machine layer ───────────────────────────────

/**
 * Bare layout used by every machine template. No nav/footer/scripts.
 * Sets a permissive Content-Type via meta tags and a simple monospace style.
 */
export const machineLayoutLiquid = `<!doctype html>
<html lang="{{ shop.locale }}">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta name="robots" content="index,follow">
  <title>{{ page_title | escape }} — {{ shop.name | escape }}</title>
  {%- if page_description -%}
  <meta name="description" content="{{ page_description | escape }}">
  {%- endif -%}
  <link rel="canonical" href="{{ canonical_url }}">
  <link rel="alternate" type="text/html" href="{{ canonical_url }}">
  <style>
    body { font-family: ui-monospace, SFMono-Regular, Menlo, monospace; max-width: 80ch; margin: 2rem auto; padding: 0 1rem; line-height: 1.55; color: #111; background: #fff; }
    h1, h2, h3 { line-height: 1.25; }
    pre { white-space: pre-wrap; word-wrap: break-word; }
    table { border-collapse: collapse; }
    td, th { border: 1px solid #999; padding: .25rem .5rem; }
    a { color: #06c; }
  </style>
</head>
<body>
{{ content_for_layout }}
</body>
</html>`;

/**
 * Renders a product as markdown-ish plain text for AI consumption.
 */
export const machineProductSection = `{%- comment -%}
  AutoAEO machine-readable product renderer. Stripped layout, structured content,
  designed for AI crawlers (ChatGPT, Claude, Perplexity, Google AI).
{%- endcomment -%}
<pre>
# {{ product.title }}

**Price:** {% if product.price_min == product.price_max %}{{ product.price | money }}{% else %}{{ product.price_min | money }} – {{ product.price_max | money }}{% endif %}
**Vendor:** {{ product.vendor }}
**Type:** {{ product.type }}
**Available:** {% if product.available %}Yes{% else %}No{% endif %}
**URL:** {{ shop.url }}{{ product.url }}
{%- if product.tags.size > 0 %}
**Tags:** {{ product.tags | join: ', ' }}
{%- endif %}

## Description
{{ product.description | strip_html | strip_newlines }}

{%- if product.options.size > 0 %}

## Options
{%- for opt in product.options_with_values %}
- {{ opt.name }}: {{ opt.values | join: ', ' }}
{%- endfor %}
{%- endif %}

{%- if product.variants.size > 1 %}

## Variants
{%- for v in product.variants %}
- {{ v.title }} — {{ v.price | money }}{% if v.sku != blank %} (SKU: {{ v.sku }}){% endif %}{% unless v.available %} (sold out){% endunless %}
{%- endfor %}
{%- endif %}

{%- if product.metafields.specs %}

## Specifications
{%- for field in product.metafields.specs %}
- {{ field | first }}: {{ field | last }}
{%- endfor %}
{%- endif %}
</pre>

<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "Product",
  "name": {{ product.title | json }},
  "description": {{ product.description | strip_html | json }},
  "image": [{% for img in product.images limit: 5 %}{{ img.src | image_url: width: 1200 | json }}{% unless forloop.last %}, {% endunless %}{% endfor %}],
  "sku": {{ product.selected_or_first_available_variant.sku | json }},
  "brand": { "@type": "Brand", "name": {{ product.vendor | json }} },
  "offers": {
    "@type": "AggregateOffer",
    "priceCurrency": {{ shop.currency | json }},
    "lowPrice": {{ product.price_min | divided_by: 100.0 | json }},
    "highPrice": {{ product.price_max | divided_by: 100.0 | json }},
    "availability": "{% if product.available %}https://schema.org/InStock{% else %}https://schema.org/OutOfStock{% endif %}",
    "url": "{{ shop.url }}{{ product.url }}"
  }
}
</script>`;

export const machineCollectionSection = `<pre>
# {{ collection.title }}

**URL:** {{ shop.url }}{{ collection.url }}
**Products:** {{ collection.products_count }}

## Description
{{ collection.description | strip_html | strip_newlines }}

## Products
{%- for product in collection.products %}
- [{{ product.title }}]({{ product.url }}?view=machine) — {{ product.price | money }}{% if product.available == false %} (sold out){% endif %}
{%- endfor %}
</pre>`;

export const machinePageSection = `<pre>
# {{ page.title }}

**URL:** {{ shop.url }}{{ page.url }}

{{ page.content | strip_html | strip_newlines }}
</pre>`;

export const machineArticleSection = `<pre>
# {{ article.title }}

**Published:** {{ article.published_at | date: "%Y-%m-%d" }}
**Author:** {{ article.author }}
**URL:** {{ shop.url }}{{ article.url }}
{%- if article.tags.size > 0 %}
**Tags:** {{ article.tags | join: ', ' }}
{%- endif %}

{{ article.content | strip_html | strip_newlines }}
</pre>`;

export const machineIndexSection = `<pre>
{{ page.content }}
</pre>`;

// ─── JSON templates that wire the sections in via template_suffix=machine ─

export function machineTemplateJson(sectionType: string): string {
  return JSON.stringify(
    {
      sections: {
        main: { type: sectionType, settings: {} },
      },
      order: ["main"],
    },
    null,
    2,
  );
}

// ─── robots.txt.liquid update ────────────────────────────────────────

/**
 * Returns a new robots.txt.liquid that is friendly to AI crawlers and lists
 * the machine sitemap. Preserves the existing default robots.txt block.
 */
export function generateRobotsTxt(args: { primaryDomain: string }): string {
  return `# AutoAEO-managed robots.txt
# Default Shopify rules:
{% for group in robots.default_groups %}
{{- group.user_agent }}
{%- for rule in group.rules %}
{{ rule }}
{%- endfor %}
{%- if group.sitemap != blank %}

{{ group.sitemap }}
{%- endif %}
{% endfor %}

# AutoAEO — explicit rules for AI crawlers
User-agent: GPTBot
Allow: /

User-agent: ChatGPT-User
Allow: /

User-agent: OAI-SearchBot
Allow: /

User-agent: ClaudeBot
Allow: /

User-agent: anthropic-ai
Allow: /

User-agent: PerplexityBot
Allow: /

User-agent: Google-Extended
Allow: /

User-agent: CCBot
Allow: /

User-agent: Applebot-Extended
Allow: /

# Machine-readable index
Sitemap: https://${args.primaryDomain}/pages/llms.txt
Sitemap: https://${args.primaryDomain}/pages/llms-full.txt
`;
}
